brascch/urls.py
"""brascch URL Configuration
"""
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # url padrão 
    path('', include('website.urls')),

    # interface administrativa 
    path('admin/', admin.site.urls),
]

website/urls.py
from website.views import About, DataVisualization, Contact
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from.import views

app_name = 'website'

#lista de roteamentos de URLs para funções/Views
urlpatterns = [
	path('', views.home, name="home"),
	path('about', About.as_view(), name="about"),
	path('datavisualization', DataVisualization.as_view(), name="datavisualization"),
	path('contact', Contact.as_view(), name="contact"),

	path('accounts/', include('django.contrib.auth.urls')),
	path('models/', views.models_list, name='models_list'),
	path('models/upload/', views.upload_Models, name="upload_models"),
	path('myAdmin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/models.py
from django.db import models

class Modelos(models.Model):
    title = models.CharField(max_length=50)
    name = models.CharField(max_length=30)
    description = models.TextField()
    instructions = models.TextField()
    predictor = models.FileField(upload_to='predictor')
    dataset = models.FileField(upload_to='dataset')


    def __str__(self):
        return self.title

forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())

website/forms.py
from django import forms

from .models import Modelos

class ModelsForm(forms.ModelForm):
    class Meta:
        model = Modelos
        fields = ('title', 'name', 'description', 'instructions', 'predictor','dataset')

website/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from .forms import ModelsForm
from .models import Modelos


@login_required
def models_list(request):
	models = Modelos.objects.all()
	return render(request, 'website/models_list.html', {
		'models': models
	})


@login_required
def upload_Models(request):
	if request.method == 'POST':
		form = ModelsForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect('models_list')
	else:
		form = ModelsForm()

	return render(request, 'website/upload_models.html', {
		'form': form
	})


def home(request):
    return render(request, 'website/index.html')


class About(TemplateView):
	template_name = "website/about.html"


class DataVisualization(TemplateView):
	template_name = "website/datavisualization.html"


class Contact(TemplateView):
	template_name = "website/contact.html"

website/templates/website/_layouts/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <meta charset="UTF-8">
  <!-- Title -->
  <meta lang="pt-br">
  <title>
    {% block title %}Plataforma de informação de mortalidade neonatal{% endblock %}
  </title>

  <!-- Favicon -->
  <!-- <link rel="shortcut icon" href="{% static 'website/img/BraSCCH.png' %}" type="image/png"> -->

  <!-- Arquivos CSS -->
  <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'website/css/master.css' %}"> 
  <link rel="stylesheet" href="{% static 'website/css/base.css' %}">

  <!-- Arquivos necessários para o Bootstrap -->
  <script src="{% static 'website/js/jquery.min.js' %}"></script>
  <script src="{% static 'website/js/bootstrap.min.js' %}"></script>

  <!-- Bloco de scripts -->
  {% block scripts %}{% endblock %}

  <!-- Scripts.js -->
  <script src="{% static 'website/js/scripts.js' %}"></script>

  <!-- Bloco de Estilos -->
  {% block styles %}{% endblock %}
</head>
<body>
  <div>
    <div>
      <img id="logo" src="{% static 'website/img/BraSCCH.png' %}" height='120px'>
    </div>
    <!-- Navegação da plataforma -->
    <div>
      <header>
        <nav class="menu">
          <ul>
            <a href="{% url 'website:home' %}"><li>Home</li></a>
            <a href="{% url 'website:about' %}"><li>About</li></a>
            <a href="{% url 'website:datavisualization' %}"><li>Data Visualization</li></a>
            <a href="{% url 'website:contact' %}"><li>Contact</li></a>
            {% if user.is_authenticated%}
            <a href="{% url 'website:logout' %}">Logout</a>
            <a href="{% url 'website:models_list' %}"><li>Models</li></a>
            <a href="{% url 'website:upload_models' %}"><li>Upload</li></a>
            {% else %}
            <a href = "{% url 'website:login' %}">Login</a>
            {% endif %}
          </ul>
        </nav>
      </header>
    </div>

    <div id="division">
      <hr> <!-- linha para divisão de conteúdos da plataforma-->
    </div>

    {% block conteudo %}{% endblock %}
  </div>
</body>
<hr> <!-- linha para divisão de conteúdos da plataforma-->
<footer>
  <p id="copyright"> © Lavínia Pedrosa</p>       
</footer>
</html>

website/templates/website/about.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}
<!-- Bloco que define o <title></title> da plataforma -->
{% block title %}BraSCCH{% endblock %}

<!-- Bloco de conteúdo da plataforma -->
{% block conteudo %}
<div>
	<div>
		<h3>BraSCCH</h3>
	</div>
	<br>
	<div>
		<p class="about">	
			The first 28 days of life – known as the neonatal period – represents the most vulnerable moment for a child’s survival and are strongly influenced by unfavorable life conditions of the population and by health care. Neonatal mortality are deaths per 1,000 live births at which babies of either less than four weeks of year of age. Mortality in this period reflects the complex conjunction of biological, socioeconomic and care factors, where the latter is mainly related to attention dedicated to the pregnant woman and the newborn. According to the World Health Organization, 4.1 million (75% of all under-five deaths) occurred within the first year of life in 2017. Globally, the infant mortality rate has decreased. Annual infant deaths have declined from 8.8 million in 1990 to 4.1 million in 2017. 
		</p>

		<p class="about">
			The main causes of neonatal deaths are congenital malformation, asphyxia during labor and perinatal infections; that is, mostly preventable deaths from health services. In Brazil, between 1999 and 2013, although the number of infant deaths declined, 70% of the deaths occurred due to preventable causes, and among the main causes, those related to adequate attention to pregnancy and delivery presented growth of about 33%.
			The reduction of neonatal mortality is extremely important because its proportion in cases of deaths up to five years continues to increase. In addition, the health interventions needed to deal with the leading causes of neonatal deaths differ from other causes.  In particular, Brazil still has worrying levels of infant mortality, despite declining rates in the last ten years.

		</p>
		<p class="about"> 
			In order to improve actions to reduce neonatal mortality in Brazil and to subsidize public policies at maternal and child health, our team have been creating the Brazilian Smart Cart for Child Health (BraSCCH) platform, which can be defined as decision-making support platform, based on information visualization techniques and machine learning.
			BraSCCH platform provides demographic, socioeconomic, maternal and child health indicators at the federal, state and municipal levels. The objective is to provide a management tool that allows both the maternal and child health situation and the context variables in which people are inserted to be known, allowing for the establishment of continuous follow-up processes (monitoring the implementation and evaluation of results). Our main proposal is to provide managers and society as a whole with useful data for the formulation of prevention policies and actions, as well as contributing to the improvement of the quality of health care and the information generated at the basic levels of care, with consequent reduction of neonatal mortality.

		</p>
		<p class="about">
			In general lines, two main services provided by BraSCCH are: (1) Cohort Data Visualization for decision-making support by comparative human visual analysis; and (2) Machine Learning Models for Prediction of risk of neonatal death. A visual analytics approaches can be a better understanding of the interactions between different factors. Complementarily, machine learning methods have great potential for this type of analysis, but are rarely used in this type of neonatal mortality study in Brazil. Thus, the application of visual analytics techniques and machine learning in this context are innovative to the Brazilian reality. With models that make such analyzes more efficient and effective, in addition to preventing neonatal deaths, it is also intended to improve the care provided to women, as there is a fragility in the integration between prenatal care and delivery care.

		</p>

	</div>
</div>

{% endblock %}

website/templates/website/contact.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}
<!-- Bloco que define o <title></title> da plataforma -->
{% block title %}BraSCCH{% endblock %}

<!-- Bloco de conteúdo da plataforma -->
{% block conteudo %}

{% endblock %}

website/templates/website/datavisualization.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}
<!-- Bloco que define o <title></title> da plataforma -->
{% block title %}BraSCCH{% endblock %}

<!-- Bloco de conteúdo da plataforma -->
{% block conteudo %}

{% endblock %}

website/templates/website/index.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da plataforma -->
{% block title %}BraSCCH{% endblock %}

<!-- Bloco de conteúdo da plataforma -->
{% block conteudo %}
<div>
	<div>
		<h1>Welcome to Brazilian Smart Care for Child Health</h1>
	</div>
	<!--infos-->
	<div>
		<table>
			<tr>
				{% load static %}     
				<td><img id="imgPI" src="{% static 'website/img/foot.png' %}"/></td>
				<td id="presentation"> BraSCCH platform provides demographic, socioeconomic, maternal and child health indicators at the federal, state and municipal levels. The objective is to provide a management tool that allows both the maternal and child health situation and the context variables in which people are inserted to be known, allowing for the establishment of continuous follow-up processes (monitoring the implementation and evaluation of results). Our main proposal is to provide managers and society as a whole with useful data for the formulation of prevention policies and actions, as well as contributing to the improvement of the quality of health care and the information generated at the basic levels of care, with consequent reduction of neonatal mortality.</td>     
			</tr>  
		</table>        
	</div>
</div> 
{% endblock %}

website/templates/website/models_list.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}
<!-- Bloco que define o <title></title> da plataforma -->
{% block title %}BraSCCH{% endblock %}

<!-- Bloco de conteúdo da plataforma -->
{% block conteudo %}
<div class="lista">
<h1>Lista Modelos:</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Nome</th>
                <th>Descriçao</th>
                <th>Instruçao</th>
                <th>Modelo</th>
            </tr>
        </thead>
        <tbody>
            {% for model in models %}
                <tr>
                    <td>{{model.title}}</td>
                    <td>{{model.name}}</td>
                    <td>{{model.description}}</td>
                    <td>{{model.instructions}}</td>
                    <td><a href="{{ model.predictor.url }}" class="btn btn-primary btn-sm">
                        Ir ate o Modelo
                    </a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

website/templates/website/upload_models.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}
<!-- Bloco que define o <title></title> da plataforma -->
{% block title %}BraSCCH{% endblock %}

<!-- Bloco de conteúdo da plataforma -->
{% block conteudo %}
<div class="upload">
<h1>Upload Models:</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form }}
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>
</div>
{% endblock %}